/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.biosislite.vistas.dialogos;

import com.biosis.biosislite.Main;
import com.biosis.biosislite.controladores.Controlador;
import com.biosis.biosislite.controladores.TipoPermisoControlador;
import com.biosis.biosislite.controladores.VacacionControlador;
import com.biosis.biosislite.entidades.AsignacionPermiso;
import com.biosis.biosislite.entidades.Periodo;
import com.biosis.biosislite.entidades.Vacacion;
import com.biosis.biosislite.entidades.escalafon.Empleado;
import com.biosis.biosislite.utiles.HerramientaGeneral;
import com.biosis.biosislite.utiles.UsuarioActivo;
import com.personal.utiles.FormularioUtil;
import com.personal.utiles.ReporteUtil;
import java.io.File;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.text.MaskFormatter;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.swingbinding.JTableBinding;
import org.jdesktop.swingbinding.SwingBindings;

/**
 *
 * @author Francis
 */
public class DlgVacacionCRUD extends javax.swing.JDialog {

    /**
     * Creates new form DlgPermisoCRU
     */
    private List<AsignacionPermiso> asignacionList;
    private Vacacion vacacion;
    private int accion;
    private final VacacionControlador vacc = new VacacionControlador();
    private final TipoPermisoControlador tpermc = new TipoPermisoControlador();
    private boolean accionRealizada = false;
    private final ReporteUtil reporteador = new ReporteUtil();
    private boolean tieneReprogramacion = false;
    private Empleado empleadoSeleccionado;

    public DlgVacacionCRUD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        iniciarMascara();
        initComponents();

        bindeoSalvaje();
        vacc.prepararCrear();
        this.vacacion = vacc.getSeleccionado();
        this.accion = Controlador.NUEVO;
        inicializar(vacacion, accion);
    }

    public DlgVacacionCRUD(JInternalFrame parent, Vacacion vacacion, int accion) {
        super(JOptionPane.getFrameForComponent(parent), true);
        iniciarMascara();
        initComponents();
        bindeoSalvaje();
        this.vacacion = vacacion;
        this.accion = comprobarAccion(vacacion, accion);
        inicializar(vacacion, accion);

        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlMantenimiento = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JLabel();
        pnlFin = new javax.swing.JPanel();
        txtFechaFin = new javax.swing.JFormattedTextField(this.mascaraFecha);
        pnlInicio = new javax.swing.JPanel();
        txtFechaInicio = new javax.swing.JFormattedTextField(this.mascaraFecha);
        pnlPeriodo = new javax.swing.JPanel();
        pnlAccionesEmpleado = new javax.swing.JPanel();
        lblCargandoPeriodo = new org.jdesktop.swingx.JXBusyLabel();
        btnHistorial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeriodo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEmpleadoNombre = new javax.swing.JTextField();
        btnEmpleados = new javax.swing.JButton();
        lblAvisoReprogramacion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        pnlInterrupcionReprogramacion = new javax.swing.JPanel();
        pnlInterrupcion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        pnlReprogramacion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTable2 = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de vacaciones");

        pnlMantenimiento.setLayout(new java.awt.BorderLayout(0, 5));

        lblTitulo.setBackground(new java.awt.Color(204, 204, 255));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Asignar vacación");
        lblTitulo.setOpaque(true);
        pnlMantenimiento.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        btnGuardar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Save_16x16.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit_16x16.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar);

        btnEliminar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Remove_16x16.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        btnImprimir.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Print_16x16.png"))); // NOI18N
        btnImprimir.setText("imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimir);

        btnCancelar.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cancel_16x16.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        pnlMantenimiento.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 5, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel3.setText("Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel3, gridBagConstraints);

        txtDocumento.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(txtDocumento, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel5.setText("Fecha de inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel5, gridBagConstraints);

        txtPeriodo.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        txtPeriodo.setText("2014-2015");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(txtPeriodo, gridBagConstraints);

        pnlFin.setLayout(new java.awt.GridBagLayout());

        txtFechaFin.setColumns(10);
        txtFechaFin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFechaFin.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        pnlFin.add(txtFechaFin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(pnlFin, gridBagConstraints);

        pnlInicio.setLayout(new java.awt.GridBagLayout());

        txtFechaInicio.setColumns(10);
        txtFechaInicio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFechaInicio.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        pnlInicio.add(txtFechaInicio, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(pnlInicio, gridBagConstraints);

        pnlPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección de período"));
        pnlPeriodo.setLayout(new java.awt.BorderLayout(0, 5));

        pnlAccionesEmpleado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        lblCargandoPeriodo.setText("Cargando saldos vacacionales");
        lblCargandoPeriodo.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        pnlAccionesEmpleado.add(lblCargandoPeriodo);

        btnHistorial.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Find_16x16.png"))); // NOI18N
        btnHistorial.setText("Ver historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        pnlAccionesEmpleado.add(btnHistorial);

        pnlPeriodo.add(pnlAccionesEmpleado, java.awt.BorderLayout.PAGE_START);

        tblPeriodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPeriodo);

        pnlPeriodo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(pnlPeriodo, gridBagConstraints);

        jLabel1.setText("Empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel1, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        txtEmpleadoNombre.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel4.add(txtEmpleadoNombre, gridBagConstraints);

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/User_16x16.png"))); // NOI18N
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel4.add(btnEmpleados, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel3.add(jPanel4, gridBagConstraints);

        lblAvisoReprogramacion.setBackground(new java.awt.Color(255, 255, 204));
        lblAvisoReprogramacion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblAvisoReprogramacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAvisoReprogramacion.setText("Aviso: Esta vacación no es susceptible a cambios debido a que ha sido reprogramada");
        lblAvisoReprogramacion.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(lblAvisoReprogramacion, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel7.setText("Fecha de fin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel7, gridBagConstraints);

        lblPeriodo.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblPeriodo.setText("Período:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(lblPeriodo, gridBagConstraints);

        pnlMantenimiento.add(jPanel3, java.awt.BorderLayout.CENTER);

        pnlPrincipal.addTab("Mantenimiento", pnlMantenimiento);

        pnlInterrupcionReprogramacion.setLayout(new java.awt.GridLayout(0, 1));

        pnlInterrupcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Interrupciones"));
        pnlInterrupcion.setLayout(new java.awt.BorderLayout());

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jXTable1);

        pnlInterrupcion.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlInterrupcionReprogramacion.add(pnlInterrupcion);

        pnlReprogramacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Reprogramación"));
        pnlReprogramacion.setLayout(new java.awt.BorderLayout());

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jXTable2);

        pnlReprogramacion.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnlInterrupcionReprogramacion.add(pnlReprogramacion);

        pnlPrincipal.addTab("Reprogramación / interrupciones", pnlInterrupcionReprogramacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        volcarData(vacc.getSeleccionado());

        if (vacc.accion(accion)) {
            FormularioUtil.mensajeExito(this, accion);
            this.accionRealizada = true;
            this.dispose();

        } else {
            FormularioUtil.mensajeError(this, accion);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.accion = Controlador.MODIFICAR;
        inicializar(vacacion, accion);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        this.accion = Controlador.ELIMINAR;
        if (JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar este permiso?", "Mensaje del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if (this.vacc.accion(accion)) {
                FormularioUtil.mensajeExito(this, accion);
                this.vacacion = null;
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        File reporte = Main.FICHERO_REPORTE_PAPELETA_SALIDA;
//        List<Long> lista = new ArrayList<>();

        Map<String, Object> parametros = new HashMap<>();
        parametros.put("permiso_id", this.vacacion.getId());
        parametros.put("por_lote", true);
        parametros.put("reporte_ususario", UsuarioActivo.getUsuario().getLogin());
        parametros.put("reporte_institucion", Main.REPORTE_INSTITUCION);

        reporteador.setConn(vacc.getDao().getConexion());
        reporteador.generarReporte(reporte, parametros, JOptionPane.getFrameForComponent(this));
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        DlgEmpleado dlgEmpleado = new DlgEmpleado(this);
        Empleado empleado = dlgEmpleado.getSeleccionado();
        if (empleado != null) {
            txtEmpleadoNombre.setText(empleado.getNombreCompleto());
            PeriodoWorker periodo = new PeriodoWorker();
            periodo.execute();
        }
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        Periodo periodo = this.periodoSeleccionado();
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgVacacionCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgVacacionCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgVacacionCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgVacacionCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        VacacionControlador vacc = new VacacionControlador();
//        Vacacion vacacion = vacc.buscarPorId(2L);
        vacc.prepararCrear();
        Vacacion vacacion = vacc.getSeleccionado();
        java.awt.EventQueue.invokeLater(() -> {
            DlgVacacionCRUD dialog = new DlgVacacionCRUD(new javax.swing.JInternalFrame(), vacacion, Controlador.NUEVO);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTable jXTable2;
    private javax.swing.JLabel lblAvisoReprogramacion;
    private org.jdesktop.swingx.JXBusyLabel lblCargandoPeriodo;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAccionesEmpleado;
    private javax.swing.JPanel pnlFin;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlInterrupcion;
    private javax.swing.JPanel pnlInterrupcionReprogramacion;
    private javax.swing.JPanel pnlMantenimiento;
    private javax.swing.JPanel pnlPeriodo;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReprogramacion;
    private javax.swing.JTable tblPeriodo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmpleadoNombre;
    private javax.swing.JFormattedTextField txtFechaFin;
    private javax.swing.JFormattedTextField txtFechaInicio;
    private javax.swing.JLabel txtPeriodo;
    // End of variables declaration//GEN-END:variables

    private MaskFormatter mascaraFecha;

    private void iniciarMascara() {
        try {
            this.mascaraFecha = new MaskFormatter("##/##/####");
            this.mascaraFecha.setPlaceholderCharacter('_');
//            this.mascara.setInvalidCharacters("A'");
        } catch (ParseException ex) {
            Logger.getLogger(DlgVacacionCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*
    NUEVO = campos en blanco
    EDITAR = campos llenos con lo que existe del permiso
    VER = campos llenos con lo que existe en el permiso sin capacidad de editar
     */
    private void inicializar(Vacacion vacacion, int accion) {
        switch (accion) {
            case Controlador.NUEVO:

                lblTitulo.setText("Asignar vacaciones");
                btnCancelar.setText("Cancelar");
                break;
            case Controlador.MODIFICAR:
                lblTitulo.setText("Modificar vacaciones");
                btnCancelar.setText("Cancelar");
                break;
            case Controlador.LEER:
                lblTitulo.setText("Ver vacaciones");
                btnCancelar.setText("Cerrar");
                break;
        }

        vacc.setSeleccionado(vacacion);

        inicializarControles(accion);
        if (accion == Controlador.MODIFICAR || accion == Controlador.LEER) {
            llenarCampos(vacacion);
        }

    }

    private void bindeoSalvaje() {
        asignacionList = ObservableCollections.observableList(new ArrayList<AsignacionPermiso>());
        BeanProperty pDocumento = BeanProperty.create("empleado.nroDocumento");
        BeanProperty pNombreCompleto = BeanProperty.create("empleado.nombreCompleto");

        JTableBinding bindTable = SwingBindings.createJTableBinding(AutoBinding.UpdateStrategy.READ, asignacionList, tblPeriodo);
        bindTable.addColumnBinding(pDocumento).setColumnName("DNI").setEditable(false);
        bindTable.addColumnBinding(pNombreCompleto).setColumnName("Apellidos y nombres").setEditable(false);

        bindTable.bind();

    }

    private void inicializarControles(int accion) {
        boolean leer = accion == Controlador.LEER;
        boolean nuevo = accion == Controlador.NUEVO;
        boolean leerModificar = accion == Controlador.LEER || accion == Controlador.MODIFICAR;
        boolean nuevoModificar = accion == Controlador.NUEVO || accion == Controlador.MODIFICAR;
        
        this.lblCargandoPeriodo.setVisible(false);

        this.btnEditar.setVisible(accion == Controlador.LEER && !tieneReprogramacion);
        this.btnEliminar.setVisible(leerModificar && !tieneReprogramacion);
        this.btnGuardar.setVisible(nuevoModificar);
        this.btnImprimir.setVisible(leer);
        this.lblPeriodo.setVisible(leer);
        this.txtPeriodo.setVisible(leer);
        this.lblAvisoReprogramacion.setVisible(tieneReprogramacion);
        this.pnlPeriodo.setVisible(nuevoModificar);
        this.btnEmpleados.setVisible(nuevo);

        this.txtDocumento.setEditable(!leer);
        this.txtFechaInicio.setEditable(!leer);
        this.txtFechaFin.setEditable(!leer);
    }

    private void llenarCampos(Vacacion vacacion) {

        this.txtDocumento.setText(vacacion.getDocumento());
        this.txtEmpleadoNombre.setText(vacacion.getEmpleado().getNombreCompleto());
        this.txtFechaInicio.setText(HerramientaGeneral.formatoFecha.format(vacacion.getFechaInicio()));
        this.txtFechaFin.setText(HerramientaGeneral.formatoFecha.format(vacacion.getFechaFin()));

        if (this.accion == Controlador.LEER) {
            int anio = vacacion.getPeriodo().getAnio();
            txtPeriodo.setText(String.format("%s - %s", anio, (anio + 1)));
        }

        this.asignacionList.clear();
    }

    private void volcarData(Vacacion permiso) {
        try {
            String strFechaInicio = this.txtFechaInicio.getText();
            String strFechaFin = this.txtFechaFin.getText();
            Date fechaInicio = HerramientaGeneral.formatoFecha.parse(strFechaInicio);
            Date fechaFin = HerramientaGeneral.formatoFecha.parse(strFechaFin);

            permiso.setFechaInicio(fechaInicio);
            permiso.setFechaFin(fechaFin);
            permiso.setDocumento(txtDocumento.getText());

        } catch (ParseException ex) {
            Logger.getLogger(DlgVacacionCRUD.class.getName()).log(Level.SEVERE, null, ex.getCause().getMessage());
        }
    }

    public Vacacion getVacacion() {
        return vacacion;
    }

    public boolean isAccionRealizada() {
        return accionRealizada;
    }

    private int comprobarAccion(Vacacion vacacion, int accion) {

        if (accion == Controlador.MODIFICAR && vacacion.getVacacionReprogramacion() != null) {
            this.tieneReprogramacion = true;
            return Controlador.LEER;
        }

        return accion;
    }

    private Periodo periodoSeleccionado() {
        int fila = tblPeriodo.getSelectedRow();
        
    }

    private class PeriodoWorker extends SwingWorker<Double, Void> {

        @Override
        protected Double doInBackground() throws Exception {
            lblCargandoPeriodo.setVisible(true);
            lblCargandoPeriodo.setBusy(true);
            btnHistorial.setEnabled(false);
            Thread.sleep(5000);
            return 100.0;
        }

        @Override
        protected void done() {
            lblCargandoPeriodo.setBusy(false);
            lblCargandoPeriodo.setVisible(false);
            btnHistorial.setEnabled(true);
        }

    }

}
