/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.biosis.biosislite.vistas;

/**
 *
 * @author Aldo
 */
public class GestionHorarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionHorarios
     */
    public GestionHorarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlHvsE = new javax.swing.JPanel();
        pnlHorariosHvsE = new javax.swing.JPanel();
        pnlParamBusquedaHvsE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaHHvsE = new javax.swing.JTextField();
        btnBuscarH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorariosHvsE = new org.jdesktop.swingx.JXTable();
        pnlButtonsHHvsE = new javax.swing.JPanel();
        btnNuevoH = new javax.swing.JButton();
        btnModificarH = new javax.swing.JButton();
        btnEliminarH = new javax.swing.JButton();
        pnlEmpleadosHvsE = new javax.swing.JPanel();
        pnlFiltroEmpleadoHvsE = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBusquedaEHvsE = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleadosHvsE = new org.jdesktop.swingx.JXTable();
        pnlButtonsEHvsE = new javax.swing.JPanel();
        btnNuevoE = new javax.swing.JButton();
        btnModificarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        btnImportarE = new javax.swing.JButton();
        pnlEvsH = new javax.swing.JPanel();
        pnlEmpleadosEvsH = new javax.swing.JPanel();
        pnlFiltroEmpleadoEvsH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarEEvsH = new javax.swing.JTextField();
        btnBuscarEEvsH = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmpleadosEvsH = new org.jdesktop.swingx.JXTable();
        pnlHorariosEvsH = new javax.swing.JPanel();
        pnlParamBusquedaEvsH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarHEvsH = new javax.swing.JTextField();
        btnBuscarHEvsH = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHorariosEvsH = new org.jdesktop.swingx.JXTable();
        pnlButtonsHEvsH = new javax.swing.JPanel();
        btnNuevoHEvsH = new javax.swing.JButton();
        btnModificarAsigHEvsH = new javax.swing.JButton();
        btnEliminarHEvsH = new javax.swing.JButton();

        setTitle("Gestión de Horarios");

        pnlHvsE.setLayout(new java.awt.GridLayout(1, 2));

        pnlHorariosHvsE.setBorder(javax.swing.BorderFactory.createTitledBorder("Horarios"));
        pnlHorariosHvsE.setLayout(new java.awt.BorderLayout());

        pnlParamBusquedaHvsE.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de búsqueda"));
        java.awt.GridBagLayout pnlParamBusquedaHLayout = new java.awt.GridBagLayout();
        pnlParamBusquedaHLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlParamBusquedaHLayout.rowHeights = new int[] {0};
        pnlParamBusquedaHvsE.setLayout(pnlParamBusquedaHLayout);

        jLabel1.setText("Nombre / Código / Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlParamBusquedaHvsE.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlParamBusquedaHvsE.add(txtBusquedaHHvsE, gridBagConstraints);

        btnBuscarH.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        pnlParamBusquedaHvsE.add(btnBuscarH, gridBagConstraints);

        pnlHorariosHvsE.add(pnlParamBusquedaHvsE, java.awt.BorderLayout.NORTH);

        tblHorariosHvsE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblHorariosHvsE);

        pnlHorariosHvsE.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlButtonsHHvsE.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        btnNuevoH.setText("Agregar Horario");
        pnlButtonsHHvsE.add(btnNuevoH);

        btnModificarH.setText("Modificar");
        pnlButtonsHHvsE.add(btnModificarH);

        btnEliminarH.setText("Eliminar");
        pnlButtonsHHvsE.add(btnEliminarH);

        pnlHorariosHvsE.add(pnlButtonsHHvsE, java.awt.BorderLayout.SOUTH);

        pnlHvsE.add(pnlHorariosHvsE);

        pnlEmpleadosHvsE.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));
        pnlEmpleadosHvsE.setLayout(new java.awt.BorderLayout());

        pnlFiltroEmpleadoHvsE.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar por:"));
        java.awt.GridBagLayout pnlFiltroEmpleadoLayout = new java.awt.GridBagLayout();
        pnlFiltroEmpleadoLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        pnlFiltroEmpleadoLayout.rowHeights = new int[] {0};
        pnlFiltroEmpleadoHvsE.setLayout(pnlFiltroEmpleadoLayout);

        jLabel2.setText("Nombres / Dni / Código Modular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlFiltroEmpleadoHvsE.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlFiltroEmpleadoHvsE.add(txtBusquedaEHvsE, gridBagConstraints);

        btnBuscarE.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlFiltroEmpleadoHvsE.add(btnBuscarE, gridBagConstraints);

        pnlEmpleadosHvsE.add(pnlFiltroEmpleadoHvsE, java.awt.BorderLayout.PAGE_START);

        tblEmpleadosHvsE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblEmpleadosHvsE);

        pnlEmpleadosHvsE.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlButtonsEHvsE.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        btnNuevoE.setText("Agregar Empleado(s)");
        pnlButtonsEHvsE.add(btnNuevoE);

        btnModificarE.setText("Modificar");
        pnlButtonsEHvsE.add(btnModificarE);

        btnEliminarE.setText("Eliminar");
        pnlButtonsEHvsE.add(btnEliminarE);

        btnImportarE.setText("Importar Empleados");
        pnlButtonsEHvsE.add(btnImportarE);

        pnlEmpleadosHvsE.add(pnlButtonsEHvsE, java.awt.BorderLayout.PAGE_END);

        pnlHvsE.add(pnlEmpleadosHvsE);

        jTabbedPane1.addTab("Horarios vs Empleados", pnlHvsE);

        pnlEvsH.setLayout(new java.awt.GridLayout(1, 2));

        pnlEmpleadosEvsH.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));
        pnlEmpleadosEvsH.setLayout(new java.awt.BorderLayout());

        pnlFiltroEmpleadoEvsH.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar por:"));
        java.awt.GridBagLayout pnlFiltroEmpleadoEvsHLayout = new java.awt.GridBagLayout();
        pnlFiltroEmpleadoEvsHLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        pnlFiltroEmpleadoEvsHLayout.rowHeights = new int[] {0};
        pnlFiltroEmpleadoEvsH.setLayout(pnlFiltroEmpleadoEvsHLayout);

        jLabel3.setText("Nombres / Dni / Código Modular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlFiltroEmpleadoEvsH.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlFiltroEmpleadoEvsH.add(txtBuscarEEvsH, gridBagConstraints);

        btnBuscarEEvsH.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        pnlFiltroEmpleadoEvsH.add(btnBuscarEEvsH, gridBagConstraints);

        pnlEmpleadosEvsH.add(pnlFiltroEmpleadoEvsH, java.awt.BorderLayout.PAGE_START);

        tblEmpleadosEvsH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblEmpleadosEvsH);

        pnlEmpleadosEvsH.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pnlEvsH.add(pnlEmpleadosEvsH);

        pnlHorariosEvsH.setBorder(javax.swing.BorderFactory.createTitledBorder("Horarios"));
        pnlHorariosEvsH.setLayout(new java.awt.BorderLayout());

        pnlParamBusquedaEvsH.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros de búsqueda"));
        java.awt.GridBagLayout pnlParamBusquedaEvsHLayout = new java.awt.GridBagLayout();
        pnlParamBusquedaEvsHLayout.columnWidths = new int[] {0, 5, 0, 5, 0};
        pnlParamBusquedaEvsHLayout.rowHeights = new int[] {0};
        pnlParamBusquedaEvsH.setLayout(pnlParamBusquedaEvsHLayout);

        jLabel4.setText("Nombre / Código / Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlParamBusquedaEvsH.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        pnlParamBusquedaEvsH.add(txtBuscarHEvsH, gridBagConstraints);

        btnBuscarHEvsH.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        pnlParamBusquedaEvsH.add(btnBuscarHEvsH, gridBagConstraints);

        pnlHorariosEvsH.add(pnlParamBusquedaEvsH, java.awt.BorderLayout.PAGE_START);

        tblHorariosEvsH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblHorariosEvsH);

        pnlHorariosEvsH.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        pnlButtonsHEvsH.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        btnNuevoHEvsH.setText("Agregar Horario");
        pnlButtonsHEvsH.add(btnNuevoHEvsH);

        btnModificarAsigHEvsH.setText("Modificar");
        pnlButtonsHEvsH.add(btnModificarAsigHEvsH);

        btnEliminarHEvsH.setText("Eliminar");
        pnlButtonsHEvsH.add(btnEliminarHEvsH);

        pnlHorariosEvsH.add(pnlButtonsHEvsH, java.awt.BorderLayout.PAGE_END);

        pnlEvsH.add(pnlHorariosEvsH);

        jTabbedPane1.addTab("Empleados vs Horario", pnlEvsH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarEEvsH;
    private javax.swing.JButton btnBuscarH;
    private javax.swing.JButton btnBuscarHEvsH;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnEliminarH;
    private javax.swing.JButton btnEliminarHEvsH;
    private javax.swing.JButton btnImportarE;
    private javax.swing.JButton btnModificarAsigHEvsH;
    private javax.swing.JButton btnModificarE;
    private javax.swing.JButton btnModificarH;
    private javax.swing.JButton btnNuevoE;
    private javax.swing.JButton btnNuevoH;
    private javax.swing.JButton btnNuevoHEvsH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlButtonsEHvsE;
    private javax.swing.JPanel pnlButtonsHEvsH;
    private javax.swing.JPanel pnlButtonsHHvsE;
    private javax.swing.JPanel pnlEmpleadosEvsH;
    private javax.swing.JPanel pnlEmpleadosHvsE;
    private javax.swing.JPanel pnlEvsH;
    private javax.swing.JPanel pnlFiltroEmpleadoEvsH;
    private javax.swing.JPanel pnlFiltroEmpleadoHvsE;
    private javax.swing.JPanel pnlHorariosEvsH;
    private javax.swing.JPanel pnlHorariosHvsE;
    private javax.swing.JPanel pnlHvsE;
    private javax.swing.JPanel pnlParamBusquedaEvsH;
    private javax.swing.JPanel pnlParamBusquedaHvsE;
    private org.jdesktop.swingx.JXTable tblEmpleadosEvsH;
    private org.jdesktop.swingx.JXTable tblEmpleadosHvsE;
    private org.jdesktop.swingx.JXTable tblHorariosEvsH;
    private org.jdesktop.swingx.JXTable tblHorariosHvsE;
    private javax.swing.JTextField txtBuscarEEvsH;
    private javax.swing.JTextField txtBuscarHEvsH;
    private javax.swing.JTextField txtBusquedaEHvsE;
    private javax.swing.JTextField txtBusquedaHHvsE;
    // End of variables declaration//GEN-END:variables
}
